# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0352df777ad125ca60788c9e2b5ec0dcd35dfbff26db460e6d02604a7f903b45c855b6a6e538fbcff1d4d1989e1412b3061975d9b6affad437b73de0b005a92

test:
  secret_key_base: 0166e07b0a9484ff0595e8f19c03e35131f20d543ca9951bdb3292b44fa6f5568aaaed7b11434212cd096ade1dd0d66643b63516b488ea3fcc9c0f6dd18af628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
